package gr.codehub.guide.filmrepository.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedNativeQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.validation.constraints.Size;

import gr.codehub.guide.filmrepository.transfer.ActorFilmsPair;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.NoArgsConstructor;

@NamedNativeQuery(
	name = "Actor.getNumOfFilmsPerActor",
	query = "select concat(a.firstname,' ', a.lastname) as actor, count(fa.film_id) as numOfFilms from actor a, " +
		"film_actor fa where a.id=fa.actor_id group by a.id order by 2 desc",
	resultSetMapping = "FilmsPerActor")
@SqlResultSetMappings({
	@SqlResultSetMapping(
		name = "FilmsPerActor",
		classes = @ConstructorResult(
			targetClass = ActorFilmsPair.class,
			columns = {
				@ColumnResult(name = "actor", type = String.class),
				@ColumnResult(name = "numOfFilms", type = Long.class)
			}
		)
	)
})

/**
 * The Actor entity.
 */
@Entity
@Data
@NoArgsConstructor
@ApiModel(description = "Entity bean containing actor's approved information")
public class Actor implements Serializable {
	private static final long serialVersionUID = -7889312197790905891L;
	/**
	 * Actor's unique id.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "actorSequence")
	@SequenceGenerator(name = "actorSequence", sequenceName = "actor_seq", allocationSize = 1)
	@ApiModelProperty(required = true, notes = "Autogenerated identifier, don't try to set its value")
	private Long id;

	/**
	 * Actor's firstname.
	 */
	@Size(min = 3, message = "Firstname should have at least 3 characters")
	@Column(length = 20, nullable = false)
	@ApiModelProperty(required = true, notes = "Actor's first name")
	private String firstName;

	/**
	 * Actor's lastname.
	 */
	@Size(min = 3, message = "Lastname should have at least 3 characters")
	@Column(length = 30, nullable = false)
	@ApiModelProperty(required = true, notes = "Actor's last name")
	private String lastName;

	@ApiModelProperty(required = false, notes = "Actor's address(es)")
	@OneToMany(mappedBy = "actor", cascade = CascadeType.ALL, targetEntity = Address.class, fetch = FetchType.LAZY)
	private List<Address> addressList = new ArrayList<>();
}
