# The spring-boot-devtools module includes an embedded LiveReload server
# that can be used to trigger a browser refresh when a resource is changed.
server:
  port: 8080
  servlet:
    context-path: ''
spring:
  application:
    name: Film Repository
  banner:
    location: classpath:banner.txt
  devtools:
    livereload:
      enabled: false
    remote:
      restart:
        enabled: false
    restart:
      additional-paths: ''
      enabled: true
      log-condition-evaluation-delta: false
    # Whether to enable development property defaults.
    add-properties: true
  output:
    ansi:
      enabled: always
